name: Docker website CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build website image
        run: |
          docker build --platform linux --tag san1994/sitiomatriculauniversitaria:latest -f Dockerfile .

      - name: Publish website image
        run: |
          docker push san1994/sitiomatriculauniversitaria:latest

      - name: App service auth
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MatriculaUniversitaria'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'san1994/sitiomatriculauniversitaria:latest'

